import Image from 'next/image'
import Link from 'next/link'
import styles from './page.module.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <main className={styles.main}>
      <h1>Home Page!</h1>
      <Link href="/users">Users Page</Link>
    </main>
  )
}
